---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: voting-application
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: voting-application
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: voting-application
    spec:
      containers:
        - name: postgres-app
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: Password
            - name: POSTGRES_USER
              value: User
            - name: POSTGRES_DB
              value: DB
...