---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: voting-application
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 90
  selector:
    name: result-pod
    app: voting-application
...
