---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    name: result-deployment
    app: voting-application
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-pod
      app: voting-application
  template:
    metadata:
      name: result-pod
      labels:
        name: result-pod
        app: voting-application
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
...

