---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker-deployment
    app: voting-application
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: voting-application
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: voting-application
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
...